# Generated by Django 5.1.6 on 2025-02-28 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Localidad',
            new_name='Localidads',
        ),
        migrations.AddField(
            model_name='boleto',
            name='localidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='examen.localidads'),
            preserve_default=False,
        ),
    ]
