# Generated by Django 5.1.6 on 2025-02-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_rename_localidad_localidads_boleto_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
